name: Android CI

on:
  push:
    branches: [ "release" ]
    tags: ["release", "pre-release"]
  pull_request:
    branches: [ "release" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - name: Change Direct
      run: cd 
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
      working-directory: ./android
    - name: Install dependencies
      run: yarn install
    - name: Build with Gradle
      run: ./gradlew assembleRelease
      working-directory: ./android
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.4.3
      with:
        # Artifact name
        name: GongGong
        path: android/app/build/outputs/apk/release/app-release.apk
